server:
  port: 9527

spring:
  application:
    name: by15-Gateway
  cloud:
    gateway:
      routes:
        - id: by15-User # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: http://localhost:8701
          predicates:
            - Path=/hello/World/** # 断言，路径相匹配的进行路由
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka
  instance:
    hostname: localhost