spring:
  application:
    name: by15-User
server:
  port: 8701 # 服务提供方
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db202111161439_medium?TNS_ADMIN=C:\\Users\\18507\\Downloads\\WINDOWS.X64_193000_db_home\\network\\admin\\Wallet
    username: admin
    password: By15KgxmLiuChong
# 指定当前eureka客户端的注册地址,
eureka:
  client:
    serviceUrl:
      defaultZone: http://129.158.37.135:8081/eureka
  instance:
    hostname: localhost
