spring:
  application:
    name: by15-AuthCenter
server:
  port: 8703 # 服务提供方
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db202111161439_medium?TNS_ADMIN=C:\Program Files\Study\By15\Wallet
    username: admin
    password: By15KgxmLiuChong
# 指定当前eureka客户端的注册地址,
eureka:
  client:
    serviceUrl:
      defaultZone: http://111.67.203.92:8081/eureka
  instance:
    hostname: localhost
